### ISSUE TITLE
Site failing to render properly in IE

### ISSUE THREAD

**Issue by DavidMGross** [ReactiveX/reactivex.github.io#84]
The dropdown menus are not behaving correctly in IE.

I'm noticing a "Popover requires tooltip.js" error in the javascript console window, from bootstrap.min.js.

**Comment by staltz** [comment]
It's possible that when bootstrap.js (and min.js) was compiled, the order of the bootstrap plugins was wrong. I've seen this error happening in other situations.

**Comment by staltz** [comment]
Would be good if I could be included in the organization for this repo so I can assign myself to some issues.

**Comment by DavidMGross** [comment]
Hmmm... not sure who to ask about that. Ben maybe? I seem to be able to
assign myself issues but if that also gives me the power to give you that
authority I can't figure out how to make it happen.

On Tue, Jan 13, 2015 at 10:32 AM, André Staltz <notifications@github.com>
wrote:

> Would be good if I could be included in the organization for this repo so
> I can assign myself to some issues.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ReactiveX/reactivex.github.io/issues/84#issuecomment-69793940>
> .
>



-- 
David M. Gross
PLP Consulting

**Comment by staltz** [comment]
@benjchristensen ?

**Comment by benjchristensen** [comment]
Done

**Comment by DavidMGross** [comment]
The javascript error is gone in IE, but the rendering is still failing (the dropdown menu contents are visible on the page even when page first loads, when the menus are not in drop-down mode, and they stay there even as the menus render and go into and out of drop-down mode)

![reactivex ie](https://cloud.githubusercontent.com/assets/4491168/6176597/049a3dda-b2b5-11e4-8e8a-a88fdbaa700d.png)

**Comment by staltz** [comment]
I just need to find myself an IE11 (I use Mac)
